ingewikkeld_rest_user:
    resource: "@IngewikkeldRestUserBundle/Controller/"
    type:     annotation

ingewikkeld_rest_oauth_server:
    resource: "@IngewikkeldRestOAuthServerBundle/Resources/config/routing.xml"
