# Example bundles

ingewikkeld_resourceful_examples_simple:
    resource: "@IngewikkeldResourcefulExamplesSimpleBundle/Resources/config/routing.yml"
    prefix:   /

# Symfony routes

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

# Normal routing

_main:
    resource: routing.yml
